[package]
name = "mandelbrot-set"
version = "0.1.0"
edition = "2021"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Mandelbrot_set"

[dependencies]
image = { version = "0.24.2", default-features = false, features = ["png"] }
num-complex = "0.4"
